name: Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --web-renderer=html
      
      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
